<?php if (!defined('APPLICATION')) exit();
// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/config.php file.

//Server-Sent Events
$Configuration['Shoutbox']['SSE']['SleepTime'] = 3;
$Configuration['Shoutbox']['SSE']['ExecLimit'] = 60;
$Configuration['Shoutbox']['SSE']['ClientReconnect'] = 5;
$Configuration['Shoutbox']['SSE']['KeepAliveTime'] = 30;

//Client config stuff
//Partial Tango Colorspalette
$Configuration['Shoutbox']['Client']['Colors'] = array(
	'#fce94f', '#edd400', 					#Butter
	'#fcaf3e', '#f57900', 					#Orange
	'#8ae234', '#4e9a06', 					#Chameleon
	'#3465a4', '#204a87', 					#Sky Blue
	'#ad7fa8', '#5c3566', 					#Plum
	'#ef2929', '#cc0000', '#a40000',#Scarlet Red
	'#2e3436'												#Aluminium
);
$Configuration['Shoutbox']['Client']['MessageLimit'] = 50;
